xcache:
  application: shop
  t0:
    charset: UTF-8
    cache-type: both
    local:
      cache-store: caffeineCacheStoreProvider
      store-name: caffeine
      initial-capacity: 1024
      maximum-size: 2048
      maximum-weight: 0
      key-strength: none
      value-strength: none
      expire-after-write: 3600000
      expire-after-access: 300000
      enable-random-ttl: true
      enable-null-value: true
      value-compressor: gzipCompressorProvider
      value-serializer: jacksonSerializerProvider
    remote:
      cache-store: lettuceCacheStoreProvider
      store-name: redis-string
      expire-after-write: 7200000
      enable-key-prefix: true
      enable-random-ttl: true
      enable-null-value: true
      value-compressor: gzipCompressorProvider
      value-serializer: jacksonSerializerProvider
    extension:
      key-convertor: jacksonKeyConvertorProvider
      cache-lock: localCacheLockProvider
      cache-lock-size: 128
      cache-stat: logCacheStatManager
      cache-sync: lettuceCacheSyncProvider
      cache-sync-channel: shop
      cache-sync-serializer: jacksonKeyConvertorProvider
      cache-loader: none
      cache-monitors: none
      contains-predicate: alwaysTruePredicateProvider
    metadata:
      s: s
  caches:
    - name: user
      template: t0
    - name: order
      template: t0
  stats:
    - id: s
      cache-stat-period: 10000
  syncs:
    - id: s
  locks:
    - id: s


  redis:
    lettuce:
      client-resources:
        io-threads-size: 4
        computation-threads-size: 4
      stores:
        - id: lettuceCacheStoreProvider
          connection: lettuceConnectionFactory
      syncs:
        - id: lettuceCacheSyncProvider
          connection: lettuceConnectionFactory
      connections:
        - id: lettuceConnectionFactory
          database: 0
          host: localhost
          port: 6379
          username: redis-admin
          password: 123456
          ssl: false
          read-timeout:
          connect-timeout:
          client-name:
          replicas:
          read-from:
          redis-type: single
          client-options:
          sentinel:
            master: mymaster
            nodes: 127.0.0.1:6378, 127.0.0.1:6379, 127.0.0.1:6380
            username: redis-admin
            password: 123456
          cluster:
            nodes: 127.0.0.1:6378, 127.0.0.1:6379, 127.0.0.1:6380
            max-redirects: 5
            refresh:
              dynamic-refresh-sources: true
              period: 60000
              adaptive: true




